### ISSUE TITLE
"uses `pandas` to save to disk the processed or generated data."

### ISSUE THREAD

**Issue by MaxLindberg** [teokem/project-work-2021-DonglinLiu#3]
The requirements have the point:
- [x] uses `pandas` to save to disk the processed or generated data.
This is fulfilled if you count the saved fitting parameters (which are technically saved by numpy, but I don't think that's a problem). Maybe the anomalies should be saved as well?

**Comment by DonglinLiu** [comment]
Thanks, I didn't notice that, now has fixed.
