### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by MaxLindberg** [teokem/project-work-2021-DonglinLiu#4]
The plots, while very nice and clear (I especially like how you point out examples in them and circle the anomalies), miss some things from the requirements list.

- [x] the figures are 89 mm wide (single column) or 183 mm wide (double column)
           this one is really hard and doesn't seem strictly neccessary, so maybe just try and insert the image in a word document or something, either as single column or double column and see so it doesn't become weird with proportions or sizes? Then the actual size in mm shouldn't matter.
- [x] the axes are labeled
- [x] the font sizes are sufficiently large
            The first two are a bit on the limit, the third I think is good (although a little spacing between the graphs wouldn't hurt), the last feels like a single column image and then the fonts on the labels would definitely be too small.
- [x] the figures are saved as rasterized images (300 dpi) or vector art 
             Just add some `plt.savefig()` for each.

**Comment by DonglinLiu** [comment]
Thank you for the valuable feedback, I changed the figsize. But as you mentioned, this size seems not that important. So for the last figure, in order to be clearer, I just set it much bigger than 89mm.
