### ISSUE TITLE
Carlos Review Summary

### ISSUE THREAD

**Issue by cdgomezo** [teokem/project-work-2021-DonglinLiu#8]
Hi @DonglinLiu, let's start with the checklist:

Documentation:
- [x] title and abstract of the project (max 300 words)
- [x] includes instructions on how to run the notebook
- [x] includes the required packages in an environment.yml file
- [x] includes a brief explanation of the reason each package/library was used
- [x] includes rich documentation using Markdown (equations, tables, links, images or videos
- [x] is reproducible, i.e., someone else should be able to redo the steps
 Input/Output:
- [x] uses pandas to read large data sets or numpy to load data from text files
- [x] uses pandas to save to disk the processed or generated data
 Scientific computing/data processing:
- [x] performs numerical operations (numpy, scipy, pandas) or manipulates, groups, and aggregates a data set (pandas)
 Data visualization:
- [x] includes at least one composite plot (inset or multiple panels)
- [x] produces publication ready quality figures (see here for an editorial guide on Graphical Excellence):
- [x] the figures are 89 mm wide (single column) or 183 mm wide (double column)
- [x] the axes are labeled
- [x] the font sizes are sufficiently large
- [x] the figures are saved as rasterized images (300 dpi) or vector art
 Version control, sharing, and archiving:
- [x] is archived in a repository with a digital object identifier (DOI)

Now, some comments about your notebook:

The notebook is really nice, you explain everything step by step and you are producing such nice figures with annotations. I consider you just need to add some labels, increase the font of the first and last figure and add the space between figures in the second figure with `fig.tight_layout()` at the end of the cell, and finally save the figures. About using `pandas` to save data could be useful to reproduce the figures without rerun the cells since it takes quite some time to run the training part.

Well done!

**Comment by DonglinLiu** [comment]
Thank you for the valuable feedback, I have fixed all the points you mentioned above.
